# Schema for the configuration files of the Escort module.

escort.config:
  type: config_object
  label: 'Escort config'
  mapping:
    regions:
      type: sequence
      label: 'Regions'
      sequence:
        type: mapping
        label: 'Region'
        mapping:
          toggle:
            type: string
            label: 'Toggle'
